name: 🐛 Bug Report
description: Report an issue or unexpected behavior in Streamerfy
title: "[Bug] <Brief description>"
labels: ["bug"]
assignees:
  - WTFBlaze

body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report

        Thanks for taking the time to report a bug! Please fill out the information below so we can fix it.

  - type: textarea
    id: description
    attributes:
      label: 📝 Description of the Bug
      description: Provide a clear and concise explanation of the issue.
      placeholder: The app crashes when I click "Connect" after entering my OAuth token...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔁 Steps to Reproduce
      description: How do you trigger the bug? Please list step-by-step instructions.
      placeholder: |
        1. Launch Streamerfy
        2. Go to Settings
        3. Click Connect
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: What did you expect to happen instead?
      placeholder: I expected the Connect button to authenticate and change to "Disconnect".
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📄 Relevant Logs or Screenshots
      description: Paste any error messages, console output, or screenshots that help identify the issue.
      placeholder: |
        ```
        [ERROR] Spotify authorization failed: Invalid token
        ```
      render: text
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: 🧩 Streamerfy Version
      description: What version of Streamerfy are you using?
      placeholder: e.g., v1.0.2
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: 🖥️ Operating System
      description: What OS are you running Streamerfy on?
      options:
        - Windows 11
        - Windows 10
        - Other
    validations:
      required: true
