name: 🛑 Append Approved Track to Global Blacklist

on:
  issues:
    types: [labeled]

jobs:
  append-blacklist:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: ⬇️ Check out the repository
        uses: actions/checkout@v4

      - name: 🧠 Extract Track ID and Append to GlobalBlacklist.txt
        id: process
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const { execSync } = require('child_process');

            const issue = context.payload.issue;
            const issueBody = issue.body;
            const issueNumber = issue.number;

            const match = issueBody.match(/open\.spotify\.com\/track\/([a-zA-Z0-9]+)/);
            if (!match) {
              core.setFailed("❌ No valid Spotify track link found in the issue body.");
              return;
            }

            const trackId = match[1];
            const filePath = path.join(process.cwd(), 'GlobalBlacklist.txt');

            let existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';

            if (existing.includes(trackId)) {
              console.log("⚠️ Track ID already exists in the blacklist.");
              core.setOutput('track_id', trackId);
              core.setOutput('issue_number', issueNumber);
              return;
            }

            // Append new line
            let cleaned = existing.trim();
            let updated = cleaned ? `${cleaned}\n${trackId}` : `${trackId}`;
            fs.writeFileSync(filePath, `${updated}\n`);

            // Git commit and push
            execSync('git config user.name "github-actions[bot]"');
            execSync('git config user.email "41898282+github-actions[bot]@users.noreply.github.com"');
            execSync(`git add "${filePath}"`);
            execSync(`git commit -m "✅ Auto-added blacklisted track: ${trackId}"`);
            execSync('git push');

            core.setOutput('track_id', trackId);
            core.setOutput('issue_number', issueNumber);

      - name: 💬 Comment on the issue
        if: steps.process.outputs.track_id != ''
        uses: actions/github-script@v7
        with:
          script: |
            const trackId = '${{ steps.process.outputs.track_id }}';
            const issueNumber = Number('${{ steps.process.outputs.issue_number }}');

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: `✅ The track \`${trackId}\` has been added to the global blacklist. Thanks for your submission!`
            });

      - name: 🛑 Close the issue
        if: steps.process.outputs.track_id != ''
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = Number('${{ steps.process.outputs.issue_number }}');

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              state: 'closed'
            });
