- name: 🧠 Extract Track ID and Append to Blacklist
  id: process
  uses: actions/github-script@v7
  with:
    script: |
      const { readFileSync, writeFileSync, existsSync } = require('fs');
      const { execSync } = require('child_process');

      const issue = context.payload.issue;
      const issueNumber = issue.number;
      const issueBody = issue.body;

      const match = issueBody.match(/open\.spotify\.com\/track\/([a-zA-Z0-9]+)/);
      if (!match) {
        core.setFailed("❌ No valid Spotify track link found in the issue body.");
        return;
      }

      const trackId = match[1];
      const filePath = 'Data/GlobalTrackBlacklist.txt';

      let existing = existsSync(filePath) ? readFileSync(filePath, 'utf8') : '';
      if (existing.includes(trackId)) {
        console.log("⚠️ Track ID already exists in the blacklist.");
        return;
      }

      existing += `\n${trackId}`;
      writeFileSync(filePath, existing.trim() + '\n');

      execSync('git config user.name "github-actions[bot]"');
      execSync('git config user.email "41898282+github-actions[bot]@users.noreply.github.com"');
      execSync('git add ' + filePath);
      execSync(`git commit -m "✅ Auto-added blacklisted track: ${trackId}"`);
      execSync('git push');

      core.setOutput('track_id', trackId);
      core.setOutput('issue_number', issueNumber.toString());
